// <auto-generated />
namespace Infrastructure.Data.SqlAzure.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Iteration4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Iteration4));
        
        string IMigrationMetadata.Id
        {
            get { return "201307091838018_Iteration4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
